[programs.Devnet]
mpl-gumdrop = "gdrpGjVffourzkdDRrQmySw4aTHr8a3xmQzzxSwFD1a"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3          # Optimize for speed.
overflow-checks = true # Enable integer overflow checks.
strip = true           # Automatically strip symbols from the binary.
